### ISSUE TITLE
TypeScriptを導入する

### ISSUE THREAD

**Issue by shogo4131** [daxi0823/yumemi_exam#4]
## 概要
- TypeScriptを導入し、現在のソースコードをTypeScriptに変更する

## ゴール
- [ ] TypeScriptを導入して現状のファイルを全て書き換える
   - tsconfig.jsonを作成する必要がある

**Comment by daxi0823** [comment]
メモ
yarn add typescript @types/node @types/react @types/react-dom -D

**Comment by daxi0823** [comment]
npx tsc --init
 tsconfig.jsonの作成
