### ISSUE TITLE
yarnを導入する

### ISSUE THREAD

**Issue by shogo4131** [daxi0823/yumemi_exam#7]
## 概要
- PCにyarnをinstallする

## ゴール
- [x] ローカルでyarnコマンドが使用できるようになる
   - yarnのコマンドでローカル環境が起動できればOK、ymlファイルできたらlockファイルを削除してPR出す

**Comment by daxi0823** [comment]
@shogo4131 
ymlファイルではなく、yarn.lockファイルが作成されました。
`yarn dev`で起動したので完了です。

**Comment by shogo4131** [comment]
OKです！
このissueは完了なのでcloseします！
